#!/bin/sh
set -e

case "${1:-}" in
    cog-ha-matter|ha-matter|homecore|homecore-server|sensing-mcp|mcp) ;;
    *)
        if [ -z "${RUVIEW_API_TOKEN:-}" ] && [ "${RUVIEW_ALLOW_UNAUTHENTICATED:-}" != "1" ]; then
            __bind_default="${RUVIEW_BIND_ADDR:-0.0.0.0}"
            case "$__bind_default" in 127.*|localhost|::1) : ;; *) echo "[entrypoint] ERROR: refusing unauthenticated network-facing sensing-server on ${__bind_default}" >&2; exit 64;; esac
        fi
        ;;
esac

case "${1:-}" in
    cog-ha-matter|ha-matter) shift; exec /app/cog-ha-matter --sensing-url "${SENSING_URL:-http://127.0.0.1:3000}" "$@" ;;
    homecore|homecore-server) shift; exec /app/homecore-server --bind "${HOMECORE_BIND:-0.0.0.0:8123}" "$@" ;;
    sensing-mcp|mcp)
        shift
        : "${RUVIEW_MCP_NEO4J_USER:?RUVIEW_MCP_NEO4J_USER must name a dedicated read-only Neo4j principal}"
        : "${RUVIEW_MCP_NEO4J_PASSWORD_ENV:=RUVIEW_MCP_NEO4J_PASSWORD}"
        : "${RUVIEW_MCP_ROOM:?RUVIEW_MCP_ROOM must scope this MCP process to one authorized room}"
        : "${RUVIEW_MCP_PRIVACY_MODE:?RUVIEW_MCP_PRIVACY_MODE must be explicitly set to true or false}"
        case "$RUVIEW_MCP_PRIVACY_MODE" in true|false) ;; *) echo "[entrypoint] ERROR: RUVIEW_MCP_PRIVACY_MODE must be true or false" >&2; exit 64;; esac
        export RUVIEW_NEO4J_USER="$RUVIEW_MCP_NEO4J_USER"
        export RUVIEW_NEO4J_ROOM="$RUVIEW_MCP_ROOM"
        exec /app/sensing-mcp --neo4j-user "$RUVIEW_MCP_NEO4J_USER" --neo4j-password-env "$RUVIEW_MCP_NEO4J_PASSWORD_ENV" --room "$RUVIEW_MCP_ROOM" "$@"
        ;;
esac

if [ "${1#-}" != "$1" ] || [ -z "$1" ]; then
    set -- /app/sensing-server --source "${CSI_SOURCE:-auto}" --tick-ms 100 --ui-path /app/ui --http-port 3000 --ws-port 3001 --bind-addr "${RUVIEW_BIND_ADDR:-0.0.0.0}" "$@"
    if [ "${RUVIEW_NEO4J:-}" = "1" ] || [ "${RUVIEW_NEO4J:-}" = "true" ]; then
        set -- "$@" --neo4j --neo4j-url "${RUVIEW_NEO4J_URL:-bolt://x1-370:7687}" --neo4j-user "${RUVIEW_NEO4J_USER:-neo4j}" --neo4j-password-env "${RUVIEW_NEO4J_PASSWORD_ENV:-NEO4J_PASSWORD}" --neo4j-room-name "${RUVIEW_NEO4J_ROOM:-main}" --neo4j-ttl-hours "${RUVIEW_NEO4J_TTL_HOURS:-168}"
    fi
fi

# Generate dashboard config with API token for UI bootstrapping.
# The token is served from the environment, not hardcoded in source.
# May fail if /app/ui/config is mounted read-only — that's fine, the
# token-bootstrap.js will fall back to prompting the user.
if [ -n "${RUVIEW_API_TOKEN:-}" ]; then
    cat > /app/ui/config/dashboard-config.js <<DASHEOF 2>/dev/null || true
// Auto-generated by entrypoint — DO NOT EDIT. Source: RUVIEW_API_TOKEN env var.
window.__RUVIEW_DASHBOARD_CONFIG = { token: "${RUVIEW_API_TOKEN}" };
DASHEOF
fi

exec "$@"
